function sensed_area= decentralized_percentage_of_sensed_area(subgraph,t,r_lim,total_area)
%Evaluate decentralized percentage of sensed area (only local coverage
%achieved by the subgraph of node-to-move) in an arbitrary step-time k

sensed_area=0;...
for ji=1:t
    xr=cell2mat(r_lim{find(subgraph(ji)),1});...
    yr=cell2mat(r_lim{find(subgraph(ji)),2});...
    area=polyarea(xr,yr);...
    sensed_area=sensed_area+area;...
end
sensed_area=(sensed_area/total_area)*100;...
return           

