function evaluate_voronoi(r,x,y,N,x1,y1)

[x1,y1]=poly2cw(x1,y1);...
for e=1:N;...
     [v,c] = voronoin([x(:) y(:)]);...
     vorx=v(c{e,1},1)  ;...        
     vory=v(c{e,1},2)  ;...   
    [vorx,vory]=poly2cw(vorx,vory);...
    [xv,yv]=polybool('&',x1,y1,vorx,vory);%vriskw thn tomh toy voronoi me ton xwro pou thelw na kalypsw 
    k=361:-1:1;...
    c2(k)=r(e)*cosd(k)+x(e);...
    d2(k)=r(e)*sind(k)+y(e);...
    [xr,yr]=polybool('&',xv,yv,c2,d2);...
    plot(xr,yr,'red')
    xr={xr};...
    yr={yr};...
    r_lim{e,1}=xr;...               %tx=cell2mat(r_lim{j,1})
    r_lim{e,2}=yr;...               %j--->xc(exterior_nodes(j))
    
    [x_pol,y_pol]=visible_polygon(x,y,x1,y1,1,r);...%visibility polygon
    [x_pol,y_pol]=poly2cw(x_pol,y_pol);...
    vispol{e,1}=x_pol;...
    vispol{e,2}=y_pol;...
    vorx=[];vory=[];xv=[];yv=[];xr=[];yr=[];x_pol=[];y_pol=[];...
      
end




% 
% 
% for j=1:N
%              k=1:1:360;...
%              c1(k)=r(j)*cosd(k)+x(j);...
%              d1(k)=r(j)*sind(k)+y(j);...
%             [v,c] = voronoin([x(:) y(:)]);...
%             for t=1:1:length(c(j,:))% krataw tis syntetagmenes twn korufwn tou voronoi tou robot #j
%                 vorx{t}=v(c{j,t},1)  ;...        
%                 vory{t}=v(c{j,t},2)  ;...   
%             end
% 
%             [xv,yv]=polybool('&',x1,y1,vorx,vory);%ta xv kai yv exoun tiw suntetagmenes twn koryfwn tou voronoi tou robot #t(se tomh me ton xwro)
%             [fx,fy] = polybool('&',xv,yv,c1,d1);% r-limited voronoi
%             
%             plot(cell2mat(fx),cell2mat(fy),'red')
%             
%             
%             
% end