function sensed_area= percentage_of_sensed_area_V2(r_lim,total_area,N)
%Evaluate percentage of sensed area in centralized way in a arbitrary time-step

sensed_area=0;...
for j=1:N
    xr=r_lim{j,1};...
    yr=r_lim{j,2};...
    area=polyarea(xr,yr);...
    sensed_area=sensed_area+area;...
end
sensed_area=(sensed_area/total_area)*100;...
return           

