function [x_pol,y_pol]=visible_polygon(x,y,x1,y1,j,r)

%returns the x-y coordinates of visible polygon for node j
% for t=1:N
    t=j;...
    xnode=x(t);...
    ynode=y(t);...    
    [x3,y3]=poly2ccw(x1,y1);...
    temp=[x3',y3'];...
    environment={temp};...
    visible_polygon=visibility_polygon( [xnode ynode] , environment , 0.000001 , 0.005 );...
    visible_polygon(end+1,:)=visible_polygon(1,:);...
    %--------circle----------
%     k=360:-1:1;
%     c2=r(t)*cosd(k)+x(t);...
%     d2=r(t)*sind(k)+y(t);...
    %------------------------
    %----visible_polygon-----
    x_pol=visible_polygon(:,1);...
    y_pol=visible_polygon(:,2);...
    %------------------------
%     %--circular visibility---
%     [xc,yc]=polybool('&',x_pol,y_pol,c2,d2);...
%     %plot(xc,yc,'red')
%     xc={xc};...
%     yc={yc};...
%     circ_visib{t,1}=xc;...               %tx=cell2mat(r_lim{j,1})
%     circ_visib{t,2}=yc;...               
%     %------------------------
%     plot(xc,yc,'red')
% end 


return