function [x_pol,y_pol]=visible_polygon_v2(x,y,x1,y1,j)

%returns the x-y coordinates of visible polygon for node j
snap_distance=0.001;...
epsilon=1e-8;...
[polx,poly]=poly2ccw(x1,y1);...

vispol={visibility_polygon([x(j) y(j)],{[polx poly]},epsilon,snap_distance)};...
VP=cell2mat(vispol);...
x_pol=VP(:,1);...
 x_pol(end+1)=x_pol(1);
y_pol=VP(:,2);...
 y_pol(end+1)=y_pol(1);
%     vispol(end+1,:)=vispol(1,:);...
    %--------circle----------
%     k=360:-1:1;
%     c2=r(t)*cosd(k)+x(t);...
%     d2=r(t)*sind(k)+y(t);...
    %------------------------
    %----visible_polygon-----

return