function [vis_nodes,x_vis,y_vis]=visible_nodes(x,y,x1,y1,j,R,r,N)
vis_nodes(1)=j;...
x_vis(1)=x(j);...
y_vis(1)=y(j);...
[x_pol,y_pol]=visible_polygon(x,y,x1,y1,j,r);...
p=2;...
for t=1:N
    if abs(t-j)>0
      in=inpolygon(x(t),y(t),x_pol,y_pol);...
      if in>=1 && sqrt((x(j)-x(t))^2+(y(j)-y(t))^2)<=R %R communication
        vis_nodes(p)=t;...
        x_vis(p)=x(t);...
        y_vis(p)=y(t);...
        p=p+1;...    
      end
    end
end
x_vis(p)=-100000;...%Needed for Voronoi plotting
x_vis(p+1)=-100000;...%...
x_vis(p+2)=100000;...%...
x_vis(p+3)=100000;...
y_vis(p)=-100000;...
y_vis(p+1)=100000;...
y_vis(p+2)=-100000;...
y_vis(p+3)=100000;...


return